### ISSUE TITLE
Support comments

### ISSUE THREAD

**Issue by bpbp-boop** [massimocandela/geofeed-validator#1]
Add support for comments in the geofeed file

```
boden@vm-noc:~$ ./geofeed-validator-linux-x64 -f geofeed/geofeed.csv 
# ip_prefix,alpha2code,region,city,postal_code Error: Not valid IP/prefix, Not valid Country Code (iso-3166-1), Not valid Subdivision Code (iso-3166-2)
 Error: Not valid IP/prefix
```

From https://datatracker.ietf.org/doc/rfc8805/

>    Feeds MUST use UTF-8 [RFC3629] character encoding.  Lines are
>    delimited by a line break (CRLF) (as specified in [RFC4180]), and
>    blank lines are ignored.  Text from a '#' character to the end of the
>    current line is treated as a comment only and is similarly ignored
>    (note that this does not strictly follow [RFC4180], which has no
>    support for comments).
> 
>    Feed lines that are not comments MUST be formatted as comma-separated
>    values (CSV), as described in [RFC4180].  Each feed entry is a text
>    line of the form:

**Comment by massimocandela** [comment]
Thanks for reporting this. This is done!

**Comment by bpbp-boop** [comment]
Thank you!
